### PR TITLE
[ZEN-357] feat: snyk code analysis with specific org header

### PR DESCRIPTION
**Pull request by Arvi3d**
https://snyksec.atlassian.net/browse/ZEN-357

### Description

feat: snyk code analysis with specific org header
Token validation logic inside deeproxy and registry expect this header to be set, in order to properly check feature flags and settings of user's org

NOTE: this PR depends on another PR https://github.com/snyk/snyk-ls/pull/229

### Checklist

- [ ] Tests added and all succeed
- [ ] Linted
- [ ] README.md updated, if user-facing
- [ ] License file updated, if new 3rd-party dependency is introduced

### Screenshots / GIFs

_Visuals that may help the reviewer. Please add screenshots for any UI change. GIFs are most welcome!_

### CODE REVIEW

**Review by bastiandoetsch — CHANGES_REQUESTED** [review]
Hey Arvyd, thanks for the PR - would you please add tests?

**Review by bastiandoetsch — APPROVED** [review]
Looks good, Arvyd. Thanks.

**Comment by bastiandoetsch** [comment]
You need to sign commits, though - so please do so and force-push :).

**Comment by Arvi3d** [comment]
> You need to sign commits, though - so please do so and force-push :).

done

**Comment by Arvi3d** [comment]
@bastiandoetsch could you please merge it?

**Pull request merged**
