### PR TITLE
fix: clipboard package not working with CGO_ENABLED=0 [ROAD-1185]

### PR DESCRIPTION
**Pull request by j-luong**
### Description

_This PR replaces the clipboard package due to compatibility issues when building with `CGO_ENABLED=0`. Before merging we will need to verify that the changes work on all platforms._

### Validation procedure

- Use goreleaser to build LS binaries in golang docker container:
```
docker run --rm -it -v ${PWD}:/app -w /app golang
go install github.com/goreleaser/goreleaser@latest
goreleaser build --rm-dist --snapshot
```
- Wire built binary as custom LS path in VSCode
- Open extension and try authenticating from scratch
- Press “Copy authentication link to clipboard”
- Auth link should be copied to clipboard (paste to verfiy)

### Checklist

- [x] Tests added and all succeed
- [x] Linted
- [x] Validated on darwin_arm64
- [ ] Validated on darwin_amd64
- [ ] Validated on linux_386
- [ ] Validated on linux_amd64
- [x] Validated on linux_arm64 (with `xsel` installed)
- [x] Validated on windows_386
- [ ] Validated on windows_amd64
- [x] License file updated, if new 3rd-party dependency is introduced

### CODE REVIEW

**Comment by j-luong** [comment]
There's a package requirement to have `xsel` or `xclip` for Linux, if these are missing, testing on `linux_arm64`, `copyAuthLink` fails with: `Snyk encountered an error: No clipboard utilities available. Please install xsel, xclip, wl-clipboard or Termux:API add-on for termux-clipboard-get/set.`

Screenshot from 2022-10-10 16-20-07

**Comment by bastiandoetsch** [comment]
Would you please the documentation to 
- readme
- gitbook

Also, please create a followup story to 
- display the needed dependency on vscode linux
- add to vscode documentation

**Comment by j-luong** [comment]
@bastiandoetsch as we're going down the 2 packages option, would the doc updates still be required? Linux shouldn't have a dependency requirement with `golang.design/x/clipboard`.

**Comment by j-luong** [comment]
Docs (README, GitBook/VSCode) have been updated.

**Review by michelkaporin — APPROVED** [review]
🚀

**Pull request merged**
