### PR TITLE
fix: Ignore IAC errors about malformed json files [ROAD-1206]

### PR DESCRIPTION
**Pull request by asaf92**
### Description

- Ignore the errors about malformed JSON files in IAC scan when there are no IAC files to be scanned.
- Adapts to new CLI output when no issues were found
- Fixes download test, avoids reporting progress to many times to save some bandwith

### Checklist

- [ ] Tests added and all succeed
- [ ] License file updated, if new 3rd-party dependency is introduced

### CODE REVIEW

**Comment by j-luong** [comment]
It wasn't clear to me, but does this account for malformed IAC files? Or does it ignore any that match the error codes?

**Comment by michelkaporin** [comment]
@j-luong it ignores results that are related to possibly malformed IaC files, that are marked with the error codes by IaC team. I.e. we don't want to error when IaC scan with CLI errors with these error codes.

**Comment by j-luong** [comment]
Ok, I would consider putting that caveat in the README or other appropriate documentation, something like `IAC scans will ignore malformed IAC files` as it may be a potential source of confusion.

**Comment by michelkaporin** [comment]
@j-luong I like being explicit to our customers about it.
@francescomari @YairZ101 is this documented somewhere within the IaC docs, such that customers are aware of such behaviour?

**Comment by YairZ101** [comment]
> is this documented somewhere within the IaC docs, such that customers are aware of such behaviour?

No, the CLI doesn't ignore malformed IaC config files, we report them as errors so we never needed to document such behavior.

**Comment by michelkaporin** [comment]
@YairZ101 right. This appears to be the desired behaviour in IDE plugins since introduction of error codes though. Does web ui also report them as errors? If not, is this documented somewhere?

Generally, what would be the right place for mentioning this?

**Comment by YairZ101** [comment]
> Does web ui also report them as errors? If not, is this documented somewhere?

yes.

> Generally, what would be the right place for mentioning this?

In my opinion, because this is a specific implementation detail for the IDE then it should be documented somewhere in the IDE docs.

**Comment by michelkaporin** [comment]
@YairZ101 thanks!
@j-luong I'll update Eclipse & IntelliJ docs after the code lands on `main` 👍

**Review by michelkaporin — APPROVED** [review]
Reviewed by @asaf92 ✅

**Pull request merged**
